# src/main/resources/application.conf

db {
  url      = "jdbc:postgresql://localhost:5433/university_management"
  user     = "postgres"
  password = "user@admin"
  driver   = "org.postgresql.Driver"

  pool {
    maximumPoolSize   = 10
    minimumIdle       = 2
    connectionTimeout = 30000   # 30 secondes en ms
    idleTimeout       = 600000  # 10 minutes en ms
  }
}

# Configuration Akka HTTP
akka {
  loglevel = "INFO"
  http {
    server {
      idle-timeout = 60s
    }
  }
}